@base_url=http://localhost:5000/api/v1/auth

###

POST {{base_url}}/register
Content-Type: application/json

{
    "name" : "utku",
    "password" : "supret",
    "email" : "utku16@foo.com",
    "role": "ADMIN"
}

###
POST {{base_url}}/login
Content-Type: application/json

{
    "email" : "utku3@foo.com",
    "password": "supret"
}

###
GET {{base_url}}/logout


