@base_url=http://localhost:5000/api/v1/auth

###

POST {{base_url}}/register
Content-Type: application/json

{
    "name" : "utku",
    "password" : "supret",
    "email" : "utku4@foo.com",
    "role": "ADMIN"
}

###
POST {{base_url}}/login

###
GET {{base_url}}/logout


