@base_url=http://localhost:5000/api/v1/products

###
GET {{base_url}}/

### 
GET {{base_url}}/2

###
DELETE {{base_url}}/4

###
POST {{base_url}}/
Content-Type: application/json

{
    "name" : "mocha",
    "price" : 45,
    "description" : "nice product",
    "image" : "asdfasfdasdfaf",
    "category" : "love",
    "company" : "milk",
    "colors" : ["yellow", "green"],
    "featured" : false,
    "inventory" : 5,
    "freeShipping" : false
}

###
PATCH  {{base_url}}/
Content-Type: application/json

{
    "name" : "mocha",
    "price" : 45,
    "description" : "nicer dicer product"
}