@base_url=http://localhost:5000/api/v1/users

###
GET {{base_url}}/

###
GET {{base_url}}/15

###
GEt {{base_url}}/showMe

###
PATCH {{base_url}}/updateUserPassword
Content-Type: application/json

{
    "oldPassword" : "supret",
    "newPassword" : "mehmet"
}

###
PATCH {{base_url}}/updateUser
Content-Type: application/json

{
    "name" : "kamil",
    "email" : "utku16@foo.com"
}